config/routes.rb
Rails.application.routes.draw do
  get "notifications/index"
  root "static_pages#top"

  devise_for :users # deviseを使用するURLに「users」を含むということ

  ### マイページ用
  get "/mypage", to: "users#show", as: "mypage" # resources :users, only: [:show]と同じルーティング
  get "/mypage/edit", to: "users#edit", as: :edit_mypage
  patch "/mypage", to: "users#update"

  ### 他人のプロフィールページ用
  resources :users, only: [ :show ] do
    # UserとFollowは関連づけられているためuserのidが必要。なのでfollowをネストする。
    member do
    get :followings  # /users/:id/followings
    get :followers   # /users/:id/followers
    end
  end

  resources :posts, only: %i[ index new create show edit update destroy ] do
    resources :comments, only: %i[ create destroy ], shallow: true
    collection do
      get :likes
      get :bookmarks
      get :autocomplete
    end
  end
  resources :follows, only: %i[ create destroy ]
  resources :likes, only: %i[ create destroy ]
  resources :bookmarks, only: %i[ create destroy ]
  resources :notification, only: %i[ index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  attr_accessor :tag_names

  validates :image, presence: { message: "を選択してください" }
  validates :title, presence: true, length: { maximum: 35 }, forbidden_word: true
  validates :body, length: { maximum: 65_535 }, forbidden_word: true
  validates :tag_names, forbidden_word: true
  validates :restaurant_info, length: { maximum: 255 }
  validates :food_info, length: { maximum: 255 }
  # 画像の拡張子
  validate :image_extension_validation

  # imageカラムにUploaderをマウントする
  mount_uploader :image, PostImageUploader

  ### タグ検索関連
  # Postモデルのカラムで検索許可するもの
  # 関連モデル（Tag）への検索でも、親（Post）側の設定として ransackable_attributes の定義が必須みたい
  # (内部的にPostの id カラムなども参照されるため）
  def self.ransackable_attributes(auth_object = nil)
    [ "id" ]
  end

  # タグ名（関連モデル）の検索も必要な場合、以下にモデル追加し、その追加したモデルファイルへもransackable_attributesで許容するカラム指定する
  def self.ransackable_associations(auth_object = nil)
    [ "tags" ]
  end

  ### tag処理
  def save_tags(input_tags) # input_tags はpostコントローラーのtag_listの中身が入る
    # 現在postにタグ付けされているか？＞ある場合は配列として取得、ない場合は空の配列[]を生成
    return unless input_tags

    current_tags = self.tags.pluck(:name)
    # 現在取得したタグから送られてきたタグを除いてold_tagとする
    old_tags = current_tags - input_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnew_tagとする
    new_tags = input_tags - current_tags

    # 不要なタグをpostから削除
    old_tags.each do |old_tag|
      self.tags.delete(Tag.find_by(name: old_tag))
    end

    # 新しいタグをpostへ追加
    new_tags.each do |new_tags|
      add_tag = Tag.find_or_create_by(name: new_tags)
      self.tags << add_tag
    end
  end

  private

  def image_extension_validation
    # return unless image.present?

    begin
      # CarrierWaveの検証（拡張子チェック）を起動させる
      image.cache! unless image.cached? # ここで拡張子NGの場合、CarrierWave::IntegrityError が発生
    rescue CarrierWave::IntegrityError => e # CarrierWave::IntegrityErrorをキャッチし、i18nへ記述した文言に変換
      errors.add(:image, :extension_whitelist_error, extension: File.extname(image.file.filename), allowed_types: image.extension_allowlist.join(", "))
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: %i[ show edit update destroy ]

  def index
    # @posts = Post.includes(:tags, :user).order(created_at: :desc)
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:tags, :user).where(users: { is_public: true }).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_list = params[:post][:tag_names].split(",") # フォームから送られたタグを,で区切った単語で配列を作っている
    @post.tag_names = tag_list.join(",") # Postインスタンスへ仮想属性tag_namesに値を代入し、バリデーション対象にする処理。
    # save_tagsメソッドだけでは post.tags << add_tag によってタグを紐付けているだけで、バリデーション対象になっていない。

    if @post.save
      @post.save_tags(tag_list) # 上記で定義したtag_list
      redirect_to posts_path, notice: t("defaults.flash_message.created", item: Post.model_name.human)
    else
      @tag_list = params[:post][:tag_names]
      flash.now[:error] = t("defaults.flash_message.not_created", item: Post.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    @post = current_user.posts.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(",")
  end

  def update
    @post = current_user.posts.find(params[:id])
    tag_list = params[:post][:tag_names].split(",") # 入力されたタグを受け取る
    @post.tag_names = tag_list.join(",")

    if @post.update(post_params)
      @post.save_tags(tag_list)
      redirect_to post_path(@post), notice: t("defaults.flash_message.updated", item: Post.model_name.human)
    else
      @tag_list = params[:post][:tag_names]
      flash.now[:error] = t("defaults.flash_message.not_updated", item: Post.model_name.human)
      render :edit, status: :unprocessable_entity
      # status: :unprocessable_entity はHTTPステータスコード 422のこと。
      # フォームバリデーションで失敗したときなどに使われる。入力エラーをユーザーに返すときに適切

    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, notice: t("defaults.flash_message.deleted", item: Post.model_name.human), status: :see_other
    # status: :see_other はHTTPステータスコード303のこと。
    # リダイレクト時に使われる。POSTのあとのGETリクエストに変換して、他のページへ遷移させたいときに便利
  end

  def likes
    @like_posts = current_user.like_posts.includes(:user).order(created_at: :desc)
  end

  def bookmarks
    @bookmark_posts = current_user.bookmark_posts.includes(:user).order(created_at: :desc)
  end

  def autocomplete
    @tags = Tag.where("name LIKE ?", "%#{params[:q]}%").limit(10)
    render layout: false # posts/autocompleteビューは候補表示だけの部分的なビューでレイアウト（application.html.erbなど）不要のため
  end

  private

  def post_params
    params.require(:post).permit(:image, :title, :image_cache, :body, :restaurant_info, :food_info)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_bookmark.html.erb
<%= link_to bookmarks_path(post_id: post.id), id: "bookmark-button-for-post-#{post.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-bookmark fs-5" style="color: #bf5320;"></i>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="mb-3" data-controller="image-preview">
    <%= f.label :image, class: "form-label d-block" %>

    <!-- 隠し file_field --><%# class: "d-none" でfile_field非表示にする %>
    <%= f.file_field :image,
          class: "d-none",
          accept: "image/*",
          data: { action: "change->image-preview#preview", image_preview_target: "file" } %>

    <!-- ラベルでボタン風に見せる -->
    <%# label for=で対応する要素（今回で言うとinput要素）のidを指定すると、input要素が選択されたように見せかけられる %>
    <label for="post_image" class="btn btn-outline-primary">
      ファイルを選択
    </label>

    <%= f.hidden_field :image_cache %>

    <div class="mt-2">
      <% if @post.image.present? %>
        <img src="<%= @post.image.url %>" data-image-preview-target="preview" class="img-fluid rounded"  id="image_preview">
      <% else %>
        <img data-image-preview-target="preview" class="img-fluid d-none rounded"  id="image_preview">
      <% end %>
    </div>
  </div>
  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", rows: "3", placeholder: "一言コメント・この一品の魅力・感想など入力してください" %>
  </div>
  <div class="mb-3">
    <%= f.label :tag_names, "タグ"%>
    <%= f.text_field :tag_names, value: @tag_list, class: "form-control", placeholder: ",で区切って入力してください(例：和食,スイーツ,コンビニなど)" %>
  </div>
  <div class="mb-3">
    <%= f.label :restaurant_info %>
    <%= f.text_field :restaurant_info, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :food_info %>
    <%= f.text_field :food_info, class: "form-control" %>
  </div>
  <%# ここのnilは新規や更新などアクションに適した文字を生成してくれる %>
  <%= f.submit nil, class: "btn btn-primary" %>
<% end %>

app/views/posts/_like.html.erb
<%= link_to likes_path(post_id: post.id), id: "like-button-for-post-#{post.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-star fs-5 text-warning"></i>
<% end %>

app/views/posts/_post.html.erb
<%= render 'shared/post_card', post: post do %>
  <%# タグの部分だけ %>
  <div class="tag-scroll-wrapper mb-2">
    <% post.tags.each do |tag| %>
      <%= link_to "##{tag.name}", posts_path(q: { tags_name_cont: tag.name }), class: "hashtag" %>
    <% end %>
  </div>
<% end %>

app/views/posts/_post_mypage.html.erb
<%= render 'shared/post_card', post: post do %>
  <%# タグの部分だけ %>
  <div class="tag-scroll-wrapper mb-2">
    <% post.tags.each do |tag| %>
      <%= link_to "##{tag.name}", @user == current_user ? mypage_path(q: { tags_name_cont: tag.name }) : user_path(@user, q: { tags_name_cont: tag.name }), class: "hashtag" %>
    <% end %>
  </div>
<% end %>

app/views/posts/_search_form.html.erb
<div class="mx-auto" style="max-width: 600px;">

  <%= search_form_for q, url: url, method: :get, class: "mb-4" do |f| %>
    <div class="search-form d-flex flex-wrap gap-2">
      <div class="flex-grow-1 position-relative"
           data-controller="autocomplete"
           data-autocomplete-url-value="<%= autocomplete_posts_path %>"
           role="combobox"
      >
        <%= f.label :tags_name_cont, "タグ名で検索", class: "form-label" %>
        <%= f.search_field :tags_name_cont,
              value: params.dig(:q, :tags_name_cont),
              class: "form-control",
              placeholder: "例: 中華",
              data: { autocomplete_target: "input" } %>

        <ul class="list-group position-absolute w-100"
            style="z-index: 1000; top: 100%;"
            data-autocomplete-target="results"></ul>
      </div>
      <div class="align-self-end">
        <%= f.submit "検索", class: "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(post_id: post.id)), id: "unbookmark-button-for-post-#{post.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-bookmark-fill fs-5" style="color: #bf5320;"></i>
<% end %>

app/views/posts/_unlike.html.erb
<%= link_to like_path(current_user.likes.find_by(post_id: post.id)), id: "unlike-button-for-post-#{post.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-star-fill fs-5 text-warning"></i>
<% end %>

app/views/posts/autocomplete.html.erb
<%# Stimulus AutocompleteがHTMLをそのまま posts/_search_formの <ul> に挿入してリスト表示してくれる %>
<% @tags.each do |tag| %>
  <li class="list-group-item"
      role="option"
      data-autocomplete-label="<%= tag.name %>"> <%# ユーザーが候補をクリックしたときに、入力欄に入れる値を指定 %>
    <%= tag.name %>
  </li>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row mb-4">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <%= render 'search_form', q: @q, url: posts_path %>
    </div>
  </div>

  <!-- 投稿一覧 -->
    <% if @posts.present? %>
      <div class="post-grid">
        <%= render @posts %>
      </div>
    <% else %>
      <div class="text-center">
        <p>投稿はまだありません。</p>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/likes.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row mb-4">
<%#
  <div class="col-lg-10 offset-lg-1">
    <!-- 検索フォーム -->
    <form>
      <div class="input-group mb-3"><input class="form-control" placeholder="検索ワード" type="search"/>
        <div class="input-group-append"><input type="submit" value="検索" class="btn btn-primary"/></div>
      </div>
    </form>
  </div>
%>
  <!-- 掲示板一覧 -->
    <% if @like_posts.present? %>
      <div class="post-grid">
        <%= render @like_posts %>
    <% else %>
      <p><%= t('.no_result') %></p>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, @post.food_info) %>

<div class="container px-3 px-md-5 my-4">
  <div class="bg-white shadow rounded py-4 px-5">
    <!-- タイトル -->
    <h4 class="fw-bold mt-2 mb-4"><%= @post.title %></h4>

    <div class="row g-lg-5">
      <!-- 左：画像＋アイコン -->
      <div class="col-md-5">

        <!-- 画像 -->
        <% if @post.image? %>
          <%= image_tag @post.image.url(:medium), class: "img-fluid rounded w-100 mb-2" %>
        <% end %>

        <!-- お気に入り・ブクマ＆編集削除 -->
        <%= render 'shared/post_actions', post: @post %>
      </div>

      <!-- 右：その他情報 -->
      <div class="col-md-7">
        <!-- アカウント名＆投稿日時 -->
        <div class="d-flex align-items-center mb-3">
          <!-- アカウント名 -->
          <%= link_to user_path(@post.user), class: "d-flex align-items-center text-decoration-none" do %>
            <i class="bi bi-person-fill fs-6 me-1" style="color: #b35900; aria-hidden="true"></i>
            <small class="fw-bold" style="color: #b35900;"><%= @post.user.name %></small>
          <% end %>
          <!-- 日時 -->
          <small class="text-muted ms-3">
            <%= time_ago_in_words(@post.created_at) %>前
            <% if @post.created_at != @post.updated_at %>
              （<%= time_ago_in_words(@post.updated_at) %>前 更新）
            <% end %>
          </small>
        </div>

        <div class="ms-1">
          <!-- 本文 -->
          <div class="mb-4">
            <%= simple_format(@post.body) %>
          </div>

          <!-- タグ --> <%# 共通化できそう %>
          <% if @post.tags.any? %>
            <div class="mb-3 tag-scroll-wrapper">
              <% @post.tags.each do |tag| %>
              <%= link_to "##{tag.name}", posts_path(q: { tags_name_cont: tag.name }), class: "hashtag" %>
              <% end %>
            </div>
          <% end %>

          <div class="ms-1">
            <!-- 食べ物情報 -->
            <% if @post.food_info.present? %>
              <div class="d-flex align-items-center mb-2">
                <i class="bi bi-fork-knife fs-6 me-2"></i>
                <!-- p.mb-0 で余計な上下マージンをリセット -->
                <p class="mb-0 small text-muted"><%= @post.food_info %></p>
              </div>
            <% end %>

            <!-- 店舗情報 -->
            <% if @post.restaurant_info.present? %>
              <div class="d-flex align-items-center mt-0 mb-2">
                <i class="bi bi-geo-alt fs-6 me-2"></i>
                <p class="mb-0 small text-muted"><%= @post.restaurant_info %></p>
              </div>
            <% end %>
          </div>
        </div>

      </div>
    </div>

    <!-- 下段：コメント欄 -->
    <div class="mt-5 border-top pt-3">
      <div class="comment-container mx-auto px-3 px-md-0">
        <%= render 'comments/form', comment: @comment, post: @post %>

        <div class="table-responsive">
          <table class="table mb-0">
            <tbody id="table-comment">
              <%= render @comments %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>